create table if not exists public.notification_fcm_tokens (
  id bigint generated by default as identity primary key,
  user_id text not null,
  token text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_webpush_subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  endpoint text not null unique,
  p256dh_key text,
  auth_key text,
  expiration_time bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_notification_fcm_tokens_user_id
  on public.notification_fcm_tokens(user_id);

create index if not exists idx_notification_webpush_user_id
  on public.notification_webpush_subscriptions(user_id);

create or replace function public.set_updated_at_timestamp()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

DROP TRIGGER IF EXISTS trg_notification_fcm_tokens_updated_at ON public.notification_fcm_tokens;
create trigger trg_notification_fcm_tokens_updated_at
before update on public.notification_fcm_tokens
for each row execute function public.set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_notification_webpush_updated_at ON public.notification_webpush_subscriptions;
create trigger trg_notification_webpush_updated_at
before update on public.notification_webpush_subscriptions
for each row execute function public.set_updated_at_timestamp();
