-- Run this once in Supabase SQL Editor
-- Creates all required tables for background claim-timer notifications

create table if not exists public.notification_fcm_tokens (
  id bigint generated by default as identity primary key,
  user_id text not null,
  token text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_webpush_subscriptions (
  id bigint generated by default as identity primary key,
  user_id text not null,
  endpoint text not null unique,
  p256dh_key text,
  auth_key text,
  expiration_time bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_timers (
  id uuid default gen_random_uuid() primary key,
  user_id text not null unique,
  timer_ends_at timestamptz not null,
  timer_duration int not null,
  created_at timestamptz default current_timestamp,
  notified boolean default false,
  updated_at timestamptz default current_timestamp
);

create index if not exists idx_notification_fcm_tokens_user_id
  on public.notification_fcm_tokens(user_id);

create index if not exists idx_notification_webpush_user_id
  on public.notification_webpush_subscriptions(user_id);

create index if not exists idx_user_timers_user_id
  on public.user_timers(user_id);

create index if not exists idx_user_timers_ends_at
  on public.user_timers(timer_ends_at);

create index if not exists idx_user_timers_notified
  on public.user_timers(notified);

create or replace function public.set_updated_at_timestamp()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

DROP TRIGGER IF EXISTS trg_notification_fcm_tokens_updated_at ON public.notification_fcm_tokens;
create trigger trg_notification_fcm_tokens_updated_at
before update on public.notification_fcm_tokens
for each row execute function public.set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_notification_webpush_updated_at ON public.notification_webpush_subscriptions;
create trigger trg_notification_webpush_updated_at
before update on public.notification_webpush_subscriptions
for each row execute function public.set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_user_timers_updated_at ON public.user_timers;
create trigger trg_user_timers_updated_at
before update on public.user_timers
for each row execute function public.set_updated_at_timestamp();

alter table public.notification_fcm_tokens enable row level security;
alter table public.notification_webpush_subscriptions enable row level security;
alter table public.user_timers enable row level security;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'notification_fcm_tokens'
      AND policyname = 'Service role can manage notification_fcm_tokens'
  ) THEN
    CREATE POLICY "Service role can manage notification_fcm_tokens"
      ON public.notification_fcm_tokens
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'notification_webpush_subscriptions'
      AND policyname = 'Service role can manage notification_webpush_subscriptions'
  ) THEN
    CREATE POLICY "Service role can manage notification_webpush_subscriptions"
      ON public.notification_webpush_subscriptions
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'user_timers'
      AND policyname = 'Service role can manage user_timers'
  ) THEN
    CREATE POLICY "Service role can manage user_timers"
      ON public.user_timers
      FOR ALL
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;
